"use client";

import { useMemo, useState } from "react";
import { documents, DRIVE_FOLDER, GITHUB_REPOSITORY } from "./libraryData";
import { DRIVE_LINKS } from "./driveLinks";
import FeaturedCourse from "./FeaturedCourse";

const NVIDIA_PROFILE = "https://www.nvidia.com/en-us/training/instructor-directory/bio/?instructorId=0038Z00002pefRaQAI";
const LINKEDIN = "https://www.linkedin.com/in/luisalbertomunozubando/";
const SCHOLAR = "https://scholar.google.com/citations?user=3o9-OssAAAAJ&hl=en";
const TEC = "https://tec.mx/";
const FINANCIERO = "https://www.elfinanciero.com.mx/opinion/alberto-munoz/";
const CV_LINK = "https://drive.google.com/drive/folders/1CHebc_zq2tqAFXia0u8DSCm8Cplog53K?usp=sharing";
const EMAIL = "mailto:amunoz@tec.mx";
const FV2K = "https://fv2k.albertomunoz.ai/";
const FV2K_IMAGE = "https://raw.githubusercontent.com/LuisAlbertoMunozUbando/FV2K/main/FV2K.jpg";
const STL = "https://stl.albertomunoz.ai/";
const INNOVACTION = "https://innovaction.albertomunoz.ai/";
const APPS_SHOWCASE = "https://raw.githubusercontent.com/LuisAlbertoMunozUbando/public/main/profile/apps-showcase.png";
const categories = ["All", ...Array.from(new Set(documents.map((document) => document.category)))];

export default function Home() {
 const [query,setQuery]=useState(""); const [category,setCategory]=useState("All");
 const filteredDocuments=useMemo(()=>{const q=query.toLowerCase().trim();return documents.filter(d=>(category==="All"||d.category===category)&&[d.title,d.type,d.category,d.description,...d.tags].join(" ").toLowerCase().includes(q));},[query,category]);
 const showFeatured=(category==="All"||category==="Artificial Intelligence")&&["desarrollo de software con ia para nvidia dgx spark curso practico completo teoria y pseudocodigo","nvidia dgx spark","ai software development","pseudocodigo","artificial intelligence"].join(" ").includes(query.toLowerCase().trim());
 return <main>
  <section className="hero" id="top">
   <nav className="nav shell"><a className="brand" href="#top" aria-label="Home"><span className="brandMark">AM</span><span>Digital Library</span></a><div className="navLinks"><a href="#profile">Profile</a><a href="#apps">Apps</a><a href="#library">Library</a><a href="#about">About</a><a className="navButton" href={DRIVE_FOLDER} target="_blank" rel="noreferrer">Open Drive ↗</a></div></nav>
   <div className="heroGrid shell"><div className="heroCopy"><div className="eyebrow">Research · Teaching · Technology</div><h1>Alberto Muñoz’s<br/><span>Digital Library</span></h1><p>A curated collection of research papers, teaching materials, technical reports and articles spanning robotics, artificial intelligence, computer vision and engineering.</p><div className="heroActions"><a className="primaryButton" href="#library">Explore the collection ↓</a><a className="secondaryButton" href={DRIVE_FOLDER} target="_blank" rel="noreferrer">Browse all PDFs ↗</a></div><div className="contactLinks"><a href={EMAIL}>✉ amunoz@tec.mx</a><a href={LINKEDIN} target="_blank" rel="noreferrer">LinkedIn ↗</a><a href={SCHOLAR} target="_blank" rel="noreferrer">Google Scholar ↗</a></div></div><div className="profileMedia"><div className="portraitPanel"><img src="/profile/alberto-munoz.jpg" alt="Dr. Alberto Muñoz"/></div><a className="cvPanel" href={CV_LINK} target="_blank" rel="noreferrer"><img src="/profile/cv.png" alt="Alberto Muñoz curriculum vitae"/><span>Open CV ↗</span></a></div></div>
   <div className="affiliations shell" id="profile"><a className="affiliationCard tec" href={TEC} target="_blank" rel="noreferrer"><img src="/profile/tec-logo.png" alt="Tecnológico de Monterrey"/></a><a className="affiliationCard nvidia" href={NVIDIA_PROFILE} target="_blank" rel="noreferrer"><img src="/profile/nvidia-logo.png" alt="NVIDIA instructor profile"/><span>NVIDIA Deep Learning Institute instructor profile ↗</span></a><div className="affiliationCard robotics"><img src="/profile/robotics-computing.png" alt="Robotics Computing"/></div><a className="affiliationCard financiero" href={FINANCIERO} target="_blank" rel="noreferrer"><img src="/profile/elfinanciero.png" alt="El Financiero"/></a></div>
   <div className="fv2kPromo shell"><a href={FV2K} target="_blank" rel="noreferrer"><img src={FV2K_IMAGE} alt="From Video to Knowledge"/><span>Explore From Video to Knowledge ↗</span></a></div>
   <div className="shell" id="apps" style={{paddingTop:"2rem",paddingBottom:"1rem"}}><div className="sectionHeading"><div><span className="kicker">AI tools & experiments</span><h2>From Ideas to Impact</h2></div><p>Explore two interactive AI tools for research, science, technology and innovation.</p></div><div style={{position:"relative",width:"100%",borderRadius:"24px",overflow:"hidden",boxShadow:"0 18px 50px rgba(15,23,42,.10)"}}><img src={APPS_SHOWCASE} alt="Science–Technology Landscape and Innovaction in Action" style={{display:"block",width:"100%",height:"auto"}}/><a href={STL} target="_blank" rel="noreferrer" aria-label="Open Science–Technology Landscape" style={{position:"absolute",left:0,top:0,width:"50%",height:"100%",zIndex:2}}></a><a href={INNOVACTION} target="_blank" rel="noreferrer" aria-label="Open Innovaction in Action" style={{position:"absolute",right:0,top:0,width:"50%",height:"100%",zIndex:2}}></a></div></div>
   <div className="stats shell"><div><strong>{documents.length+1}</strong><span>documents online</span></div><div><strong>30+</strong><span>years in research</span></div><div><strong>100+</strong><span>theses supervised</span></div></div>
  </section>
  <section id="library" className="library shell"><div className="sectionHeading"><div><span className="kicker">Curated knowledge</span><h2>Explore the library</h2></div><p>Search the complete collection by subject, title or keyword. Each card opens its corresponding public PDF.</p></div><div className="toolbar"><label className="searchBox"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search publications, topics or keywords…" aria-label="Search library"/></label><div className="filters">{categories.map(item=><button key={item} className={category===item?"active":""} onClick={()=>setCategory(item)}>{item}</button>)}</div></div><div className="resultLine"><span>{filteredDocuments.length+(showFeatured?1:0)} documents</span><span>Updated 2026</span></div><div className="documentGrid">{showFeatured&&<FeaturedCourse/>}{filteredDocuments.map(document=>{const pdfUrl=DRIVE_LINKS[document.cover]??DRIVE_FOLDER;return <article className="documentCard" key={document.title}><a className="cover" href={pdfUrl} target="_blank" rel="noreferrer"><img src={document.cover} alt={`Cover of ${document.title}`} onError={e=>{e.currentTarget.style.display="none";}}/><span className="coverIcon">{document.icon}</span><span className="coverType">{document.type}</span><span className="coverYear">{document.year}</span></a><div className="cardBody"><div className="meta"><span>{document.category}</span><span>•</span><span>{document.year}</span></div><h3>{document.title}</h3><p>{document.description}</p><div className="tags">{document.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="resourceLinks"><a className="resourceLink primary" href={pdfUrl} target="_blank" rel="noreferrer"><span>Open PDF</span><span>↗</span></a><a className="resourceLink secondary" href={GITHUB_REPOSITORY} target="_blank" rel="noreferrer"><span>GitHub</span><span>↗</span></a></div></div></article>})}</div>{filteredDocuments.length===0&&!showFeatured&&<div className="emptyState"><span>🔎</span><h3>No documents found</h3><p>Try another keyword or choose a different category.</p></div>}</section>
  <section id="about" className="about"><div className="aboutInner shell"><div><span className="kicker">About the collection</span><h2>Knowledge made open, useful and connected.</h2></div><div><p>This library brings together work in robotics, computer vision, artificial intelligence, embedded systems and engineering education.</p><p>The collection is intended for students, researchers, educators and practitioners. Original authorship and source attribution should always be preserved.</p><div className="aboutLinks"><a href={EMAIL}>amunoz@tec.mx</a><a href={LINKEDIN} target="_blank" rel="noreferrer">LinkedIn ↗</a><a href={SCHOLAR} target="_blank" rel="noreferrer">Google Scholar ↗</a><a href={DRIVE_FOLDER} target="_blank" rel="noreferrer">Google Drive archive ↗</a></div></div></div></section>
  <footer className="footer shell"><div className="brand"><span className="brandMark">AM</span><span>Alberto Muñoz’s Digital Library</span></div><p>Research · Teaching · Technology</p><a href={GITHUB_REPOSITORY} target="_blank" rel="noreferrer">GitHub ↗</a></footer>
 </main>;
}
